'use strict';
angular.module('module.service')

.factory('barService', function () {
  return {
    getBars: function () {
      return [
        { id: 'Allen.St..Grill', name : 'Allen St. Grill', lat:'40.794302', lon:'-77.861613' },
        { id: 'Bar.Bleu', name : 'Bar Bleu', lat:'40.79773', lon:'-77.856613' },
        { id: 'The.Brewery', name : 'The Brewery', lat:'40.794952', lon:'-77.858437' },
        { id: 'Cafe.210', name : 'Cafe 210', lat:'40.793246', lon:'-77.862986' },
        { id: 'Chilis', name : 'Chilis', lat:'40.793864', lon:'-77.860543' },
        { id: 'Chrome', name : 'Chrome', lat:'40.791849', lon:'-77.862299' },
        { id: 'Chumleys', name : 'Chumley\'s', lat:'40.794188', lon:'-77.861763' },
        { id: 'Darkhorse.Tavern', name : 'Darkhorse Tavern', lat:'40.79466', lon:'-77.860218' },
        { id: 'Gingerbread.Man', name : 'Gingerbread Man', lat:'40.796706', lon:'-77.856849' },
        { id: 'Indigo', name : 'Indigo', lat:'40.794123', lon:'-77.861806' },
        { id: 'Inferno', name : 'Inferno', lat:'40.797535', lon:'-77.857321' },
        { id: 'Kildares', name : 'Kildares', lat:'40.800109', lon:'-77.85379' },
        { id: 'Levels', name : 'Levels', lat:'40.798233', lon:'-77.85627' },
        { id: 'Lions.Den', name : 'Lion\'s Den', lat:'40.797523', lon:'-77.856519' },
        { id: 'Local.Whiskey', name : 'Local Whiskey', lat:'40.793683', lon:'-77.860092' },
        { id: 'Mad.Mex', name : 'Mad Mex', lat:'40.793872', lon:'-77.85852' },
        { id: 'The.Phyrst', name : 'The Phyrst', lat:'40.793683', lon:'-77.860092' },
        { id: 'Bill.Pickles.Tap.Room', name : 'Bill Pickles Tap Room', lat:'40.794156', lon:'-77.861386' },
        { id: 'The.Rathskeller', name : 'The Rathskeller', lat:'40.795151', lon:'-77.860357' },
        { id: 'Rotellis', name : 'Rotellis', lat:'40.795699', lon:'-77.858772' },
        { id: 'Rumors.Lounge', name : 'Rumors Lounge', lat:'40.791536', lon:'-77.864552' },
        { id: 'The.Saloon', name : 'The Saloon', lat:'40.797315', lon:'-77.857395' },
        { id: 'The.Shandygaff', name : 'The Shandygaff', lat:'40.795301', lon:'-77.859534' },
        { id: 'The.Tavern.Restaurant', name : 'The Tavern Restaurant', lat:'40.795677', lon:'-77.859783' },
        { id: 'Z.Bar...The.Deli', name : 'Z Bar @ The Deli', lat:'40.797133', lon:'-77.857179' },
        { id: 'Zenos', name : 'Zenos', lat:'40.79432', lon:'-77.861621' }
      ];
    },
    getSpecials: function () {
      return [
            getSpecials: function () {
      return [
	{ id: 'Allen.St..Grill', days: 'M-Sun', times: 'Allday', description: '$2 Yuengling Lager and Miller Lite Drafts, $3 ASG Teas' },
      	{ id: 'Allen.St..Grill', days: 'MSun', times: '10pm-11pm', description: '1/2 off Wells and House Chard and Cab.' },
      	{ id: 'Allen.St..Grill', days: 'T-Sat', times: '10pm-12am', description: '1/2 off Wells and House Chard and Cab.' },
      	{ id: 'Allen.St..Grill', days: 'F', times: '5pm-7pm', description: '1/2 off Wells and House Chard and Cab.' },
      	{ id: 'Allen.St..Grill', days: 'F', times: '5pm-7pm', description: '1/2 off Wells and House Chard and Cab.' },
      	{ id: 'Bar.Bleu', days: 'M-Sun', times: 'Allday', description: '$7 Captain Morgan Pitchers, $4 Fireballs, $5.75 Miller Lite, Coors Light & Bud Light Pitchers, $3.50 Yards Drafts, $3.50 Shock Top Drafts, $3.75 Blue Moon, Leinenkugel, Sam Adams Drafts' },
      	{ id: 'Bar.Bleu', days: 'Sun-Th', times: '9pm-11pm', description: '1/2 price Happies' },
      	{ id: 'Bar.Bleu', days: 'FS', times: '8pm-10pm', description: '1/2 price Happies' },
      	{ id: 'Bar.Bleu', days: 'Sun', times: 'Allday', description: '$3 Sailor Jerry Drinks' },
      	{ id: 'Bar.Bleu', days: 'M', times: 'Allday', description: '$3 Bud Light 23oz Drafts' },
      	{ id: 'Bar.Bleu', days: 'T', times: 'Allday', description: '$3 Miller Lite 23oz Drafts' },
      	{ id: 'Bar.Bleu', days: 'W', times: 'Allday', description: '$3 Labatt Blue 20oz Drafts' },
      	{ id: 'Bar.Bleu', days: 'Th', times: 'Allday', description: '$5 Fishbowls' },
      	{ id: 'Bar.Bleu', days: 'F', times: 'Allday', description: '$7 Bacardi Oakheart Pitchers' },
      	{ id: 'Bar.Bleu', days: 'S', times: 'Allday', description: '$5 Fishbowls' },
      	{ id: 'Bar.Bleu', days: 'Sun-W', times: 'until 9pm', description: '$5 wings' },
      	{ id: 'The.Brewery', days: 'None', times: 'N/A', description: 'N/A' },
	{ id: 'Cafe.210', days: 'Sun-Thurs', times: '9pm-11pm', description: '1/2 price Drinks/Drafts/Appetizers' },
	{ id: 'Cafe.210', days: 'F', times: '6pm-8pm', description: '1/2 price Drinks/Drafts/Appetizers' },
	{ id: 'Cafe.210', days: 'S', times: '9pm-11pm', description: '1/2 price Drinks/Drafts' },
	{ id: 'Cafe.210', days: 'M', times: 'Allday', description: '$2.50 Cafe Teas, $2.50 Bud Light bottle, $2.50 Burger Baskets (w/Fries)' },
	{ id: 'Cafe.210', days: 'T', times: 'Allday', description: '$3.50 23 oz Sam Adams, $7 Capt. Morgan Pitchers, $1 off Salads, $1 off Wings' },
	{ id: 'Cafe.210', days: 'W', times: 'Allday', description: '$3.00 20oz Redds Apple Ale Drafts, $3.50 Pulled Pork Baskets' },
	{ id: 'Cafe.210', days: 'Th', times: 'Allday', description: '$2.50 Cafe Teas, $4.50 Cafe Tea Picters, $1 off Wraps' },
	{ id: 'Cafe.210', days: 'F', times: 'Allday', description: '$6 Bud Light Pitchers, $1 off All Buffalo Items' },
	{ id: 'Cafe.210', days: 'S', times: 'Allday', description: '$3.50 Blue Moon 23 oz Drafts, $7 Bacardi Oakheart Pitchers, $9.95 Burger of the Week (w/soup du jour)' },
	{ id: 'Cafe.210', days: 'Sun', times: 'Allday', description: '$3.50 Goose Island 24 oz Draft, $2 Nachos' },
	{ id: 'Darkhorse.Tavern', days: 'M', times: 'until 12am', description: '$2.50 pints of Ottos Red Mo' },
	{ id: 'Chilis', days: 'None', times: 'N/A', description: 'N/A' },
	{ id: 'Chrome', days: 'M-Sun', times: 'Allday', description: '$3 Heineken, Labatt, Yuengling, Bud Light, & Miller Lite, Jose Cuervo Shots, Our Shot List (16 Mixed Shots), Chromie Drinks' },
	{ id: 'Chrome', days: 'TW', times: '9pm-12am', description: '$3 Mixed Drinks' },
	{ id: 'Chrome', days: 'ThSun', times: '10pm-12am', description: '1/2 Price Everything including All Top Shelf' },
	{ id: 'Chrome', days: 'FS', times: '10pm-12am', description: '$3 Smirnoff Flavors, $4 Mixed Drinks' },
	{ id: 'Chumleys', days: 'Sun', times: 'until 12am', description: '1/2 price Elk Creek beer' },
	{ id: 'Darkhorse.Tavern', days: 'T-Th', times: '10pm-12am', description: 'Happy Hour Half-price mixed drinks and draft beers, $3 Tonto’s Demise' },
	{ id: 'Darkhorse.Tavern', days: 'T', times: '10pm-12am', description: '$2.50 pints of Blue Moon' },
        { id: 'Darkhorse.Tavern', days: 'MTh', times: '7pm-11pm', description: '$4.95/dz wings' },
	{ id: 'Darkhorse.Tavern', days: 'T', times: '6pm-10pm', description: '$4.95 all burgers' },
	{ id: 'Darkhorse.Tavern', days: 'W', times: 'until 12am', description: '$2.50 pints of Otto's' },
	{ id: 'Darkhorse.Tavern', days: 'W', times: '6pm-1pm', description: '$4.95 all chicken sandwhiches' },
	{ id: 'Darkhorse.Tavern', days: 'Th', times: '10pm-12am', description: '$1.75 pints of Bud Light' },
	{ id: 'Darkhorse.Tavern', days: 'F', times: '6pm-8pm', description: 'Happy Hour Half-price mixed drinks and draft beers, $3 Tonto’s Demise' },
	{ id: 'Darkhorse.Tavern', days: 'F', times: 'until 12am', description: '$2 Pinnacle drinks' },
	{ id: 'Darkhorse.Tavern', days: 'S', times: '9pm-11pm', description: 'Half price well drinks' },
	{ id: 'Darkhorse.Tavern', days: 'Sun', times: '6pm-10pm', description: '$3.95 Jumbo, specialty Hebrew National dogs' },
	{ id: 'Darkhorse.Tavern', days: 'Sun', times: '10pm-12am', description: 'Happy Hour Half-price mixed drinks and draft beers' },
	{ id: 'Darkhorse.Tavern', days: 'Sun', times: '6pm-12am', description: '$2.50 pints of Troegs Hopback' },
	{ id: 'Gingerbread.Man', days: 'M-Sun', times: 'Allday', description: '$2.50 23 oz Miller Lite Drafts, $3 Mind Erasers & G-Spots, $2 Soco & Lime Shots, $3 Bacardi Flavor Mixers (excludes Red Bull)' },
	{ id: 'Gingerbread.Man', days: 'Sun', times: 'Allday', description: '$5 Coors Light Pitchers, $3 Burger/Cheeseburgers/Fries' },
	{ id: 'Gingerbread.Man', days: 'Sun', times: '10pm-12am', description: '$5 32 oz Jack Pitchers' },
	{ id: 'Gingerbread.Man', days: 'T', times: 'Allday', description: '$5 Bud Light Pitchers (open-mid), $5 Crown Royal/Crown Black/Crown Maple (open-mid)s' },
	{ id: 'Gingerbread.Man', days: 'M', times: 'Allday', description: '$5 Dew & a Brew, $2 24 oz Coors Light Cans, $3 Coors Light Pitchers, $3 Burger/Cheeseburgers/Fries' },
	{ id: 'Indigo', days: 'Sun', times: 'Allday', description: '$3 Blue Moon Draft' },
	{ id: 'Inferno', days: 'M-Sun', times: 'Allday', description: '$4 SinS, $7 Captain Morgan Pitchers, $4 Fireballs, $5.25 Miller Lite & Bud Light Pitchers, $3.50 Yards Drafts, $3.75 Blue Moon Drafts' },
	{ id: 'Inferno', days: 'Sun-Th', times: '9pm-11pm', description: '1/2 price Happies' },
	{ id: 'Inferno', days: 'FS', times: '8pm-10pm', description: '1/2 price Happies' },
	{ id: 'Inferno', days: 'M', times: 'Allday', description: '$3 Jack Daniels Drinks' },
	{ id: 'Inferno', days: 'W', times: 'Allday', description: '$3 Sailor Jerry Drinks' },
	{ id: 'Inferno', days: 'F', times: 'Allday', description: '$7 Bacardi Oakheart Pitchers' },
	{ id: 'Inferno', days: 'S', times: 'Allday', description: '$5.50 Yuenling Pitchers' },
	{ id: 'Kildares', days: 'None', times: 'N/A', description: 'N/A' },
	{ id: 'Levels', days: 'None', times: 'N/A', description: 'N/A' },
	{ id: 'Lions.Den', days: 'None', times: 'N/A', description: 'N/A' },
	{ id: 'Local.Whiskey', days: 'None', times: 'N/A', description: 'N/A' },
        { id: 'Mad.Mex', days: 'W', times: '8pm-12pm', description: '1/2 price on all food' },
	{ id: 'The.Phyrst', days: 'None', times: 'N/A', description: 'N/A' },
	{ id: 'Bill.Pickles.Tap.Room', days: 'None', times: 'N/A', description: 'N/A' },
	{ id: 'The.Rathskeller', days: 'None', times: 'N/A', description: 'N/A' },
	{ id: 'Rotellis', days: 'None', times: 'N/A', description: 'N/A' },
	{ id: 'Rumors.Lounge', days: 'None', times: 'N/A', description: 'N/A' },
	{ id: 'The.Saloon', days: 'Sun-Th', times: '9pm-11pm', description: '1/2 price Happies' },
	{ id: 'The.Saloon', days: 'FS', times: '8pm-10pm', description: '1/2 price Happies' },
	{ id: 'The.Saloon', days: 'Sun', times: 'Allday', description: '$5 Monkey Boys' },
	{ id: 'The.Saloon', days: 'M', times: 'Allday', description: '$3 Jack Daniels Drinks' },
	{ id: 'The.Saloon', days: 'T', times: 'Allday', description: '$5 Monkey Boys' },
	{ id: 'The.Saloon', days: 'W', times: 'Allday', description: '$3 Sailor Jerry Drinks' },
	{ id: 'The.Saloon', days: 'Th', times: 'Allday', description: '$5 Monkey Boys' },
	{ id: 'The.Saloon', days: 'F', times: 'Allday', description: '$7 Bacardi Oakheart Pitchers' },
	{ id: 'The.Saloon', days: 'S', times: 'Allday', description: '$5.50 Yuengling Pitchers' },
	{ id: 'The.Saloon', days: 'Sun', times: 'until 11pm', description: '$5 Wings' },
	{ id: 'The.Saloon', days: 'M', times: 'until 11pm', description: '$5 Burgers' },
	{ id: 'The.Saloon', days: 'T', times: 'until 11pm', description: '$2 Fries' },
	{ id: 'The.Saloon', days: 'W', times: 'until 11pm', description: '$1 Pizza Slices' },
	{ id: 'The.Shandygaff', days: 'None', times: 'N/A', description: 'N/A' },
	{ id: 'The.Tavern.Restaurant', days: 'None', times: 'N/A', description: 'N/A' },
	{ id: 'Z.Bar...The.Deli', days: 'M-Sun', times: 'Allday', description: '$4 Bar Zen, $7 Captain Morgan Pitchers, $4 Fireballs, $5.75 Miller Lite, $3.50 Yards Drafts, $3.75 Blue Moon Drafts' },
	{ id: 'Z.Bar...The.Deli', days: 'Sun-Th', times: '9pm-11pm', description: '1/2 price Spirits, $2 off Most Drafts' },
	{ id: 'Z.Bar...The.Deli', days: 'FS', times: '8pm-10pm', description: '1/2 price Spirits, $2 off Most Drafts' },
      	{ id: 'Z.Bar...The.Deli', days: 'M', times: 'Allday', description: '$3 Jack Daniels Drinks' },
	{ id: 'Z.Bar...The.Deli', days: 'W', times: 'Allday', description: '$3 Sailor Jerry Drinks' },
	{ id: 'Z.Bar...The.Deli', days: 'F', times: 'Allday', description: '$7 Bacardi Oakheart Pitchers' },
	{ id: 'Z.Bar...The.Deli', days: 'S', times: 'Allday', description: '$5.50 Yuenling Pitchers' },
	{ id: 'Zenos', days: 'None', times: 'N/A', description: 'N/A' }
      ];
    }
  };
});
