'use strict';
angular.module('module.service')

.factory('barService', function () {
  return {
    getBars: function () {
      return [
        { id: 'Allen.St..Grill', name : 'Allen St. Grill', lat:'40.794302', lon:'-77.861613' },
        { id: 'Bar.Bleu', name : 'Bar Bleu', lat:'40.79773', lon:'-77.856613' },
        { id: 'The.Brewery', name : 'The Brewery', lat:'40.794952', lon:'-77.858437' },
        { id: 'Cafe.210', name : 'Cafe 210', lat:'40.793246', lon:'-77.862986' },
        { id: 'Chilis', name : 'Chilis', lat:'40.793864', lon:'-77.860543' },
        { id: 'Chrome', name : 'Chrome', lat:'40.791849', lon:'-77.862299' },
        { id: 'Chumleys', name : 'Chumley\'s', lat:'40.794188', lon:'-77.861763' },
        { id: 'Darkhorse.Tavern', name : 'Darkhorse Tavern', lat:'40.79466', lon:'-77.860218' },
        { id: 'Gingerbread.Man', name : 'Gingerbread Man', lat:'40.796706', lon:'-77.856849' },
        { id: 'Indigo', name : 'Indigo', lat:'40.794123', lon:'-77.861806' },
        { id: 'Inferno', name : 'Inferno', lat:'40.797535', lon:'-77.857321' },
        { id: 'Kildares', name : 'Kildares', lat:'40.800109', lon:'-77.85379' },
        { id: 'Levels', name : 'Levels', lat:'40.798233', lon:'-77.85627' },
        { id: 'Lions.Den', name : 'Lion\'s Den', lat:'40.797523', lon:'-77.856519' },
        { id: 'Local.Whiskey', name : 'Local Whiskey', lat:'40.793683', lon:'-77.860092' },
        { id: 'Mad.Mex', name : 'Mad Mex', lat:'40.793872', lon:'-77.85852' },
        { id: 'The.Phyrst', name : 'The Phyrst', lat:'40.793683', lon:'-77.860092' },
        { id: 'Bill.Pickles.Tap.Room', name : 'Bill Pickles Tap Room', lat:'40.794156', lon:'-77.861386' },
        { id: 'The.Rathskeller', name : 'The Rathskeller', lat:'40.795151', lon:'-77.860357' },
        { id: 'Rotellis', name : 'Rotellis', lat:'40.795699', lon:'-77.858772' },
        { id: 'Rumors.Lounge', name : 'Rumors Lounge', lat:'40.791536', lon:'-77.864552' },
        { id: 'The.Saloon', name : 'The Saloon', lat:'40.797315', lon:'-77.857395' },
        { id: 'The.Shandygaff', name : 'The Shandygaff', lat:'40.795301', lon:'-77.859534' },
        { id: 'The.Tavern.Restaurant', name : 'The Tavern Restaurant', lat:'40.795677', lon:'-77.859783' },
        { id: 'Z.Bar...The.Deli', name : 'Z Bar @ The Deli', lat:'40.797133', lon:'-77.857179' },
        { id: 'Zenos', name : 'Zenos', lat:'40.79432', lon:'-77.861621' }
      ];
    },

    getSpecials: function () {
      return [
        { id: 'Allen.St..Grill', days: 'M-Sun', times: 'Allday', description: '$2 Yuengling Lager and Miller Lite Drafts, $3 ASG Teas' },
        { id: 'Allen.St..Grill', days: 'MSun', times: '10pm-11pm', description: '1/2 off Wells and House Chard and Cab.' },
        { id: 'Allen.St..Grill', days: 'T-Sat', times: '10pm-12am', description: '1/2 off Wells and House Chard and Cab.' },
        { id: 'Allen.St..Grill', days: 'F', times: '5pm-7pm', description: '1/2 off Wells and House Chard and Cab.' },
        { id: 'Allen.St..Grill', days: 'F', times: '5pm-7pm', description: '1/2 off Wells and House Chard and Cab.' },
        { id: 'Bar.Bleu', days: 'M-Sun', times: 'Allday', description: '$7 Captain Morgan Pitchers, $4 Fireballs, $5.75 Miller Lite, Coors Light & Bud Light Pitchers, $3.50 Yards Drafts, $3.50 Shock Top Drafts, $3.75 Blue Moon, Leinenkugel, Sam Adams Drafts' },
        { id: 'Bar.Bleu', days: 'Sun-Th', times: '9pm-11pm', description: '1/2 price Happies' },
        { id: 'Bar.Bleu', days: 'FS', times: '8pm-10pm', description: '1/2 price Happies' },
        { id: 'Bar.Bleu', days: 'Sun', times: 'Allday', description: '$3 Sailor Jerry Drinks' },
        { id: 'Bar.Bleu', days: 'M', times: 'Allday', description: '$3 Bud Light 23oz Drafts' },
        { id: 'Bar.Bleu', days: 'T', times: 'Allday', description: '$3 Miller Lite 23oz Drafts' },
        { id: 'Bar.Bleu', days: 'W', times: 'Allday', description: '$3 Labatt Blue 20oz Drafts' },
        { id: 'Bar.Bleu', days: 'Th', times: 'Allday', description: '$5 Fishbowls' },
        { id: 'Bar.Bleu', days: 'F', times: 'Allday', description: '$7 Bacardi Oakheart Pitchers' },
        { id: 'Bar.Bleu', days: 'S', times: 'Allday', description: '$5 Fishbowls' },
        { id: 'Bar.Bleu', days: 'Sun-W', times: 'until 9pm', description: '$5 wings' },
        { id: 'The.Brewery', days: 'None', times: 'N/A', description: 'N/A' },
        { id: 'Cafe.210', days: 'Sun-Thurs', times: '9pm-11pm', description: '1/2 price Drinks/Drafts/Appetizers' },
        { id: 'Cafe.210', days: 'F', times: '6pm-8pm', description: '1/2 price Drinks/Drafts/Appetizers' },
        { id: 'Cafe.210', days: 'S', times: '9pm-11pm', description: '1/2 price Drinks/Drafts' },
        { id: 'Cafe.210', days: 'M', times: 'Allday', description: '$2.50 Cafe Teas, $2.50 Bud Light bottle, $2.50 Burger Baskets (w/Fries)' },
        { id: 'Cafe.210', days: 'T', times: 'Allday', description: '$3.50 23 oz Sam Adams, $7 Capt. Morgan Pitchers, $1 off Salads, $1 off Wings' },
        { id: 'Cafe.210', days: 'W', times: 'Allday', description: '$3.00 20oz Redds Apple Ale Drafts, $3.50 Pulled Pork Baskets' },
        { id: 'Cafe.210', days: 'Th', times: 'Allday', description: '$2.50 Cafe Teas, $4.50 Cafe Tea Picters, $1 off Wraps' },
        { id: 'Cafe.210', days: 'F', times: 'Allday', description: '$6 Bud Light Pitchers, $1 off All Buffalo Items' },
        { id: 'Cafe.210', days: 'S', times: 'Allday', description: '$3.50 Blue Moon 23 oz Drafts, $7 Bacardi Oakheart Pitchers, $9.95 Burger of the Week (w/soup du jour)' },
        { id: 'Cafe.210', days: 'Sun', times: 'Allday', description: '$3.50 Goose Island 24 oz Draft, $2 Nachos' },
        { id: 'Darkhorse.Tavern', days: 'M', times: 'until 12am', description: '$2.50 pints of Ottos Red Mo' },
        { id: 'Chilis', days: 'None', times: 'N/A', description: 'N/A' },
        { id: 'Chrome', days: 'M-Sun', times: 'Allday', description: '$3 Heineken, Labatt, Yuengling, Bud Light, & Miller Lite, Jose Cuervo Shots, Our Shot List (16 Mixed Shots), Chromie Drinks' },
        { id: 'Chrome', days: 'TW', times: '9pm-12am', description: '$3 Mixed Drinks' },
        { id: 'Chrome', days: 'ThSun', times: '10pm-12am', description: '1/2 Price Everything including All Top Shelf' },
        { id: 'Chrome', days: 'FS', times: '10pm-12am', description: '$3 Smirnoff Flavors, $4 Mixed Drinks' },
        { id: 'Chumleys', days: 'Sun', times: 'until 12am', description: '1/2 price Elk Creek beer' },
        { id: 'Darkhorse.Tavern', days: 'T-Th', times: '10pm-12am', description: 'Happy Hour Half-price mixed drinks and draft beers, $3 Tonto’s Demise' },
        { id: 'Darkhorse.Tavern', days: 'T', times: '10pm-12am', description: '$2.50 pints of Blue Moon' },
        { id: 'Darkhorse.Tavern', days: 'MTh', times: '7pm-11pm', description: '$4.95/dz wings' },
        { id: 'Darkhorse.Tavern', days: 'T', times: '6pm-10pm', description: '$4.95 all burgers' },
        { id: 'Darkhorse.Tavern', days: 'W', times: 'until 12am', description: '$2.50 pints of Otto\'s' },
        { id: 'Darkhorse.Tavern', days: 'W', times: '6pm-1pm', description: '$4.95 all chicken sandwhiches' },
        { id: 'Darkhorse.Tavern', days: 'Th', times: '10pm-12am', description: '$1.75 pints of Bud Light' },
        { id: 'Darkhorse.Tavern', days: 'F', times: '6pm-8pm', description: 'Happy Hour Half-price mixed drinks and draft beers, $3 Tonto’s Demise' },
        { id: 'Darkhorse.Tavern', days: 'F', times: 'until 12am', description: '$2 Pinnacle drinks' },
        { id: 'Darkhorse.Tavern', days: 'S', times: '9pm-11pm', description: 'Half price well drinks' },
        { id: 'Darkhorse.Tavern', days: 'Sun', times: '6pm-10pm', description: '$3.95 Jumbo, specialty Hebrew National dogs' },
        { id: 'Darkhorse.Tavern', days: 'Sun', times: '10pm-12am', description: 'Happy Hour Half-price mixed drinks and draft beers' },
        { id: 'Darkhorse.Tavern', days: 'Sun', times: '6pm-12am', description: '$2.50 pints of Troegs Hopback' },
        { id: 'Gingerbread.Man', days: 'Sun', times: 'Allday', description: '$5 Coors Light Pitchers, $3 Burger/Cheeseburgers/Fries' },
        { id: 'Gingerbread.Man', days: 'Sun', times: '10pm-12am', description: '$5 32 oz Jack Pitchers' },
        { id: 'Gingerbread.Man', days: 'M', times: 'Allday', description: '$5 Bud Light Pitchers, 25 cent wings in orders of 10' },
        { id: 'Gingerbread.Man', days: 'M', times: '10pm-12am', description: '$2 Bacardi Oakheart Doubles' },
        { id: 'Gingerbread.Man', days: 'T', times: 'Allday', description: '$5 Miller Lite Pitchers, $3 Cheeseteaks & Fries' },
        { id: 'Gingerbread.Man', days: 'T', times: '10pm-12am', description: '$3 Red Bull Vodka' },
        { id: 'Gingerbread.Man', days: 'W', times: 'Allday', description: '$1.50 Leinenkugel Pints, $2 Cheese Nachos, $3 Beef/Chicken Nachos' },
        { id: 'Gingerbread.Man', days: 'W', times: '10pm-12am', description: '$2 Bacardi Mixers' },
        { id: 'Gingerbread.Man', days: 'Th', times: 'Allday', description: '$2 Mickey\'s Grenades, $3 16 inch Pizzas' },
        { id: 'Gingerbread.Man', days: 'Th', times: '10pm-12am', description: '$5 Flavored Ice Tea Pitchers' },
        { id: 'Gingerbread.Man', days: 'F', times: 'Allday', description: '$5 Bud Light Pitchers, $3 1/4lb Hot Dog w/Fries' },
        { id: 'Gingerbread.Man', days: 'F', times: '10pm-12am', description: '$5 Lifesaver Pitchers' },
        { id: 'Gingerbread.Man', days: 'S', times: 'Allday', description: '$5 Coors Light Pitchers, $3 1/4lb Hot Dog w/Fries' },
        { id: 'Gingerbread.Man', days: 'S', times: '10pm-12am', description: '$5 Hurricanes' },
        { id: 'Indigo', days: 'Sun', times: 'Allday', description: '$3 Blue Moon Draft' },
        { id: 'Inferno', days: 'M-Sun', times: 'Allday', description: '$4 SinS, $7 Captain Morgan Pitchers, $4 Fireballs, $5.25 Miller Lite & Bud Light Pitchers, $3.50 Yards Drafts, $3.75 Blue Moon Drafts' },
        { id: 'Inferno', days: 'Sun-Th', times: '9pm-11pm', description: '1/2 price Happies' },
        { id: 'Inferno', days: 'FS', times: '8pm-10pm', description: '1/2 price Happies' },
        { id: 'Inferno', days: 'M', times: 'Allday', description: '$3 Jack Daniels Drinks' },
        { id: 'Inferno', days: 'W', times: 'Allday', description: '$3 Sailor Jerry Drinks' },
        { id: 'Inferno', days: 'F', times: 'Allday', description: '$7 Bacardi Oakheart Pitchers' },
        { id: 'Inferno', days: 'S', times: 'Allday', description: '$5.50 Yuenling Pitchers' },
        { id: 'Kildares', days: 'M', times: 'Allday', description: '$3 Victory Pints, $7.95 All U Can Eat Wings & Fries' },
        { id: 'Kildares', days: 'M', times: '10pm-12am', description: '$3 Drafts,Long Island Iced Teas, Fireball' },
        { id: 'Kildares', days: 'T', times: 'Allday', description: '$3 Blue Moon Pints, $5 1/2lb Burger' },
        { id: 'Kildares', days: 'T', times: '10pm-12am', description: '$2 Well Pints, $3 Drafts & Long Island Iced Teas' },
        { id: 'Kildares', days: 'W', times: 'Allday', description: '$5 Pubwiches, $3 Brewery of the Month' },
        { id: 'Kildares', days: 'W', times: '10pm-12am', description: '$3 Bombs, $3 Kildare\'s Cocktails' },
        { id: 'Kildares', days: 'Th', times: 'Allday', description: '$3 Goose Island, $5 Nachos' },
        { id: 'Kildares', days: 'Th', times: '10pm-12am', description: '1/2 Off Everything' },
        { id: 'Kildares', days: 'F', times: 'Allday', description: '$3 Troeg, $9.99 Fish @ Chips' },
        { id: 'Kildares', days: 'F', times: '10pm-12am', description: '1/2 Off Liquor and Drafts' },
        { id: 'Kildares', days: 'S', times: 'Allday', description: '$3 Sam Adams' },
        { id: 'Kildares', days: 'Sun', times: 'Allday', description: '$10 Irish Entrees, $3 Big Arse 22 oz Yuengling, $3 Whiskey' },
        { id: 'Kildares', days: 'Sun', times: '10pm-12am', description: '1/2 Off Apps, $3 Drafts' },
        { id: 'Levels', days: 'None', times: 'N/A', description: 'N/A' },
        { id: 'Lions.Den', days: 'M-Sun', times: 'Allday', description: '$6 Smirnoff Flavor Pitchers, $6 Long Island Iced Tea Pitchers, $3 Bacardi & Colas, $3 Long Island Iced Teas, $2 16 oz Bud Light Bottles, $2 SoCo & Lime Shots' },
        { id: 'Lions.Den', days: 'T', times: '10pm-12am', description: '$2 U-Call-Itz (All drinks are only $2)' },
        { id: 'Lions.Den', days: 'W-S', times: '10pm-12am', description: '1/2 Price Mix Drinks and Shots' },
        { id: 'Local.Whiskey', days: 'None', times: 'N/A', description: 'N/A' },
        { id: 'Mad.Mex', days: 'M-F', times: '4:30pm-6:30pm', description: '$7 Big Azz Margaritas, $3 12 oz and $5 16 oz House Margaritas, Half off All Drafts and Wings' },
        { id: 'Mad.Mex', days: 'T-Sat', times: '9pm-12am', description: '$7 Big Azz Margaritas' },
        { id: 'Mad.Mex', days: 'T-Sat', times: '10pm-12am', description: 'Half Off Food' },
        { id: 'Mad.Mex', days: 'M-Th', times: '2pm-4pm', description: 'Half Off Food with Valid Student ID' },
        { id: 'Mad.Mex', days: 'M', times: '4pm-10pm', description: '$5 All You Can Eat Mini Burritos' },
        { id: 'Mad.Mex', days: 'M', times: '4pm-12am', description: '$5 Big Azz 22oz Margaritas' },
        { id: 'Mad.Mex', days: 'Sun', times: 'Allday', description: '$3 Big Azz 22oz Dos Equis' },
        { id: 'Mad.Mex', days: 'Sun', times: 'starting at 2pm', description: '$1 Tacos' },
        { id: 'The.Phyrst', days: 'M', times: 'Allday', description: '$2.50 Beer Cocktails' },
        { id: 'The.Phyrst', days: 'M', times: '10pm-12am', description: '1/2 Price Everything' },
        { id: 'The.Phyrst', days: 'T', times: 'Allday', description: '$2 Red Bull Vodka' },
        { id: 'The.Phyrst', days: 'W', times: 'Allday', description: '$2 Long Island Ice Teas' },
        { id: 'The.Phyrst', days: 'TWSun', times: '9pm-11pm', description: '1/2 Price Everything' },
        { id: 'The.Phyrst', days: 'Th', times: 'Allday', description: '$6.25 Buckets of Bud Light' },
        { id: 'The.Phyrst', days: 'Th', times: '8pm-10pm', description: '1/2 Price Everything' },
        { id: 'The.Phyrst', days: 'F', times: 'Allday', description: '$1 Coors Light Drafts' },
        { id: 'The.Phyrst', days: 'S', times: 'Allday', description: '$3 Pinnacle Drinks' },
        { id: 'The.Phyrst', days: 'FS', times: '7pm-9pm', description: '1/2 Price Everything' },
        { id: 'The.Phyrst', days: 'Sun', times: 'Allday', description: '$2 Blue Moon Drafts' },
        { id: 'Bill.Pickles.Tap.Room', days: 'M-Sun', times: 'Allday', description: '$2 Miller Lite & Yuengling Lager Drafts, $3 Iced T\'s' },
        { id: 'Bill.Pickles.Tap.Room', days: 'MSun', times: '10pm-11pm', description: '1/2 Off Well Liquor & House Chard & Cab' },
        { id: 'Bill.Pickles.Tap.Room', days: 'T-Sat', times: '10pm-12am', description: '1/2 Off Well Liquor & House Chard & Cab' },
        { id: 'Bill.Pickles.Tap.Room', days: 'M', times: 'Allday', description: '$3 Dos Equis Drafts, $9 Dos Equis Pitchers' },
        { id: 'Bill.Pickles.Tap.Room', days: 'TThSun', times: 'Allday', description: '$3 Shock Top Drafts, $9 Shock Top Pitchers' },
        { id: 'Bill.Pickles.Tap.Room', days: 'W', times: 'Allday', description: '$3 Sam Adams Boston Lager Drafts, $9 Sam Adams Boston Lager Pitchers' },
        { id: 'Bill.Pickles.Tap.Room', days: 'FS', times: 'Allday', description: '$3 Blue Moon Drafts, $9 Blue Moon Pitchers' },
        { id: 'The.Rathskeller', days: 'M-Th', times: '5pm-7pm', description: '$3 Premium Draft Pints, Call Liquor, House Shots' },
        { id: 'The.Rathskeller', days: 'F', times: '5pm-9pm', description: '$3 Premium Draft Pints, Call Liquor, House Shots' },
        { id: 'The.Rathskeller', days: 'M', times: 'Allday', description: '$3 Guinness Pints' },
        { id: 'The.Rathskeller', days: 'T', times: 'Allday', description: '$3 Sierra Seasonal Pints' },
        { id: 'The.Rathskeller', days: 'W', times: 'Allday', description: '$3 Stella Pints' },
        { id: 'The.Rathskeller', days: 'Th', times: 'Allday', description: '$3 Sailor Jerry' },
        { id: 'The.Rathskeller', days: 'F', times: 'Allday', description: '$3 3-Olives' },
        { id: 'The.Rathskeller', days: 'S', times: 'Allday', description: '$3 Jack Daniels' },
        { id: 'The.Rathskeller', days: 'M-W', times: '5pm-7pm', description: '$5 Flat Bread Pizza' },
        { id: 'The.Rathskeller', days: 'FS', times: '5pm-7pm', description: 'Free Munchies' },
        { id: 'Rotellis', days: 'M-Sun', times: '9pm-11pm', description: '$3 Smirnoff Drinks and $3 Micros' },
        { id: 'Rotellis', days: 'M', times: 'Allday', description: '$3 Bacardi Drinks' },
        { id: 'Rotellis', days: 'M', times: '9pm-11pm', description: 'Free Pizza' },
        { id: 'Rotellis', days: 'T', times: 'Allday', description: '$2 Labatt and Labatt Light Bottles' },
        { id: 'Rotellis', days: 'W', times: 'Allday', description: '$3 Sam Adams' },
        { id: 'Rotellis', days: 'Th', times: 'Allday', description: '$2.50 Bud Light Bottles' },
        { id: 'Rotellis', days: 'F', times: 'Allday', description: '$2 Blue Moon Drafts' },
        { id: 'Rotellis', days: 'S', times: 'Allday', description: '$2.50 Bud Light Pounder Drafts' },
        { id: 'Rotellis', days: 'Sun', times: 'Allday', description: '$2.50 Miller Light Pounder Drafts' },
        { id: 'Rumors.Lounge', days: 'None', times: 'N/A', description: 'N/A' },
        { id: 'The.Saloon', days: 'Sun-Th', times: '9pm-11pm', description: '1/2 price Happies' },
        { id: 'The.Saloon', days: 'FS', times: '8pm-10pm', description: '1/2 price Happies' },
        { id: 'The.Saloon', days: 'Sun', times: 'Allday', description: '$5 Monkey Boys' },
        { id: 'The.Saloon', days: 'M', times: 'Allday', description: '$3 Jack Daniels Drinks' },
        { id: 'The.Saloon', days: 'T', times: 'Allday', description: '$5 Monkey Boys' },
        { id: 'The.Saloon', days: 'W', times: 'Allday', description: '$3 Sailor Jerry Drinks' },
        { id: 'The.Saloon', days: 'Th', times: 'Allday', description: '$5 Monkey Boys' },
        { id: 'The.Saloon', days: 'F', times: 'Allday', description: '$7 Bacardi Oakheart Pitchers' },
        { id: 'The.Saloon', days: 'S', times: 'Allday', description: '$5.50 Yuengling Pitchers' },
        { id: 'The.Saloon', days: 'Sun', times: 'until 11pm', description: '$5 Wings' },
        { id: 'The.Saloon', days: 'M', times: 'until 11pm', description: '$5 Burgers' },
        { id: 'The.Saloon', days: 'T', times: 'until 11pm', description: '$2 Fries' },
        { id: 'The.Saloon', days: 'W', times: 'until 11pm', description: '$1 Pizza Slices' },
        { id: 'The.Shandygaff', days: 'None', times: 'N/A', description: 'N/A' },
        { id: 'The.Tavern.Restaurant', days: 'T', times: 'Allday', description: '$1 off Captain Morgan Drinks' },
        { id: 'The.Tavern.Restaurant', days: 'W', times: 'Allday', description: '$1 off Bacardi Drinks' },
        { id: 'The.Tavern.Restaurant', days: 'W', times: '5:30pm-7:30pm', description: '$3.50 Ottos Beers, 50 cents Off all House Wines by the Glass, $1 Off Bartenders Choice Wine by the Glass' },
        { id: 'The.Tavern.Restaurant', days: 'Th', times: 'Allday', description: '$5.75 Yuenling Lager Pitchers, $1 Off House Tequila Drinks' },
        { id: 'The.Tavern.Restaurant', days: 'Th', times: '5:30pm-7:30pm,10pm-12am', description: '$3 Corona Bottles' },
        { id: 'Z.Bar...The.Deli', days: 'M-Sun', times: 'Allday', description: '$4 Bar Zen, $7 Captain Morgan Pitchers, $4 Fireballs, $5.75 Miller Lite, $3.50 Yards Drafts, $3.75 Blue Moon Drafts' },
        { id: 'Z.Bar...The.Deli', days: 'Sun-Th', times: '9pm-11pm', description: '1/2 price Spirits, $2 off Most Drafts' },
        { id: 'Z.Bar...The.Deli', days: 'FS', times: '8pm-10pm', description: '1/2 price Spirits, $2 off Most Drafts' },
        { id: 'Z.Bar...The.Deli', days: 'M', times: 'Allday', description: '$3 Jack Daniels Drinks' },
        { id: 'Z.Bar...The.Deli', days: 'W', times: 'Allday', description: '$3 Sailor Jerry Drinks' },
        { id: 'Z.Bar...The.Deli', days: 'F', times: 'Allday', description: '$7 Bacardi Oakheart Pitchers' },
        { id: 'Z.Bar...The.Deli', days: 'S', times: 'Allday', description: '$5.50 Yuenling Pitchers' },
        { id: 'Zenos', days: 'None', times: 'N/A', description: 'N/A' }
      ];
    }
  };
});
